all:
	g++ -Wall -W -lm -lboost_thread -lpthread -lgpg3100 -lgpg3300 -lgpg6204 -o ArmControllerTest ArmControllerTest.cpp ArmController.cpp MotorController.cpp MC_PEX361316.cpp
#	g++ -Wall -W -lm -lboost_thread -lpthread -lgpg3100 -lgpg3300 -lgpg6204 -o testX testX.cpp MC_PEX361316.cpp MotorController.cpp
#	g++ -Wall -W -lm -lboost_thread -lpthread -lgpg3100 -lgpg3300 -lgpg6204 -o testY testY.cpp MC_PEX361316.cpp MotorController.cpp
