// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "AHCommonDataService.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace AHCommon { 
  const CORBA::TypeCode_ptr _tc_AHCommonDataService = CORBA::TypeCode::PR_interface_tc("IDL:AHCommon/AHCommonDataService:1.0", "AHCommonDataService", &_0RL_tcTrack);
} 
#else
const CORBA::TypeCode_ptr AHCommon::_tc_AHCommonDataService = CORBA::TypeCode::PR_interface_tc("IDL:AHCommon/AHCommonDataService:1.0", "AHCommonDataService", &_0RL_tcTrack);
#endif

static void _0RL_AHCommon_mAHCommonDataService_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_AHCommon_mAHCommonDataService_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(AHCommon::AHCommonDataService::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_AHCommon_mAHCommonDataService_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(CORBA::Any& _a, AHCommon::AHCommonDataService_ptr _o)
{
  AHCommon::AHCommonDataService_ptr _no = AHCommon::AHCommonDataService::_duplicate(_o);
  _a.PR_insert(AHCommon::_tc_AHCommonDataService,
               _0RL_AHCommon_mAHCommonDataService_marshal_fn,
               _0RL_AHCommon_mAHCommonDataService_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(CORBA::Any& _a, AHCommon::AHCommonDataService_ptr* _op)
{
  _a.PR_insert(AHCommon::_tc_AHCommonDataService,
               _0RL_AHCommon_mAHCommonDataService_marshal_fn,
               _0RL_AHCommon_mAHCommonDataService_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = AHCommon::AHCommonDataService::_nil();
}

CORBA::Boolean operator>>=(const CORBA::Any& _a, AHCommon::AHCommonDataService_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(AHCommon::_tc_AHCommonDataService,
                    _0RL_AHCommon_mAHCommonDataService_unmarshal_fn,
                    _0RL_AHCommon_mAHCommonDataService_marshal_fn,
                    _0RL_AHCommon_mAHCommonDataService_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (AHCommon::AHCommonDataService_ptr)_r->_ptrToObjRef(AHCommon::AHCommonDataService::_PD_repoId);
    else
      _o = AHCommon::AHCommonDataService::_nil();
    return 1;
  }
  return 0;
}

