// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __AHCommonDataService_hh__
#define __AHCommonDataService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE AHCommon

_CORBA_MODULE_BEG

#ifndef __AHCommon_mAHCommonDataService__
#define __AHCommon_mAHCommonDataService__

  class AHCommonDataService;
  class _objref_AHCommonDataService;
  class _impl_AHCommonDataService;
  
  typedef _objref_AHCommonDataService* AHCommonDataService_ptr;
  typedef AHCommonDataService_ptr AHCommonDataServiceRef;

  class AHCommonDataService_Helper {
  public:
    typedef AHCommonDataService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_AHCommonDataService, AHCommonDataService_Helper> AHCommonDataService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_AHCommonDataService,AHCommonDataService_Helper > AHCommonDataService_out;

#endif

  // interface AHCommonDataService
  class AHCommonDataService {
  public:
    // Declarations for this interface type.
    typedef AHCommonDataService_ptr _ptr_type;
    typedef AHCommonDataService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_AHCommonDataService :
    public virtual CORBA::Object,
    public virtual omniObjRef
  {
  public:
    CORBA::Boolean getData(const char* dataname, CORBA::String_out data);

    inline _objref_AHCommonDataService()  { _PR_setobj(0); }  // nil
    _objref_AHCommonDataService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_AHCommonDataService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_AHCommonDataService(const _objref_AHCommonDataService&);
    _objref_AHCommonDataService& operator = (const _objref_AHCommonDataService&);
    // not implemented

    friend class AHCommonDataService;
  };

  class _pof_AHCommonDataService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_AHCommonDataService() : _OMNI_NS(proxyObjectFactory)(AHCommonDataService::_PD_repoId) {}
    virtual ~_pof_AHCommonDataService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_AHCommonDataService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_AHCommonDataService();

    virtual CORBA::Boolean getData(const char* dataname, CORBA::String_out data) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const CORBA::TypeCode_ptr _tc_AHCommonDataService;

_CORBA_MODULE_END



_CORBA_MODULE POA_AHCommon
_CORBA_MODULE_BEG

  class AHCommonDataService :
    public virtual AHCommon::_impl_AHCommonDataService,
    public virtual PortableServer::ServantBase
  {
  public:
    virtual ~AHCommonDataService();

    inline ::AHCommon::AHCommonDataService_ptr _this() {
      return (::AHCommon::AHCommonDataService_ptr) _do_this(::AHCommon::AHCommonDataService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_AHCommon
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(CORBA::Any& _a, AHCommon::AHCommonDataService_ptr _s);
void operator<<=(CORBA::Any& _a, AHCommon::AHCommonDataService_ptr* _s);
CORBA::Boolean operator>>=(const CORBA::Any& _a, AHCommon::AHCommonDataService_ptr& _s);



inline void
AHCommon::AHCommonDataService::_marshalObjRef(::AHCommon::AHCommonDataService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_AHCommonDataService
#endif

#endif  // __AHCommonDataService_hh__

